### I. NumPy: Основы Вычислений с Массивами

**NumPy (Numerical Python)** — фундаментальная библиотека Python для научных вычислений. Предоставляет мощный объект **многомерного массива (`ndarray`)** и инструменты для работы с ним.

**Зачем NumPy?**
*   **Производительность:** Операции с `ndarray` реализованы на C, что **значительно быстрее** стандартных списков Python. Критично для ML.
*   **Удобство:** Предоставляет компактные и выразительные операции над массивами (векторизация).
*   **Функциональность:** Широкий набор математических функций, операций линейной алгебры, генерации случайных чисел и др.

**`ndarray` (N-dimensional array):**
*   Основной объект NumPy.
*   Хранит элементы **одного типа данных (`dtype`)** (e.g., `int64`, `float64`). Это обеспечивает эффективность по памяти и скорости.
*   **Ключевые атрибуты:**
    *   `.dtype`: Тип данных элементов.
    *   `.ndim`: Количество измерений (осей) массива (1 для вектора, 2 для матрицы и т.д.).
    *   `.shape`: Кортеж, показывающий размер массива по каждому измерению (e.g., `(n,)` для вектора, `(m, n)` для матрицы).

In [2]:
import numpy as np

# Создание из списка Python
python_list = [1, 2, 3, 4, 5]
np_array = np.array(python_list)
print("Массив:", np_array)
print("Тип:", type(np_array))         # <class 'numpy.ndarray'>
print("Dtype:", np_array.dtype)       # int64 (зависит от системы)
print("Ndim:", np_array.ndim)         # 1
print("Shape:", np_array.shape)       # (5,)

python_matrix_list = [[1, 2], [3, 4]]
np_matrix = np.array(python_matrix_list)
print("\nМатрица:\n", np_matrix)
print("Dtype:", np_matrix.dtype)       # int64
print("Ndim:", np_matrix.ndim)         # 2
print("Shape:", np_matrix.shape)       # (2, 2)

Массив: [1 2 3 4 5]
Тип: <class 'numpy.ndarray'>
Dtype: int32
Ndim: 1
Shape: (5,)

Матрица:
 [[1 2]
 [3 4]]
Dtype: int32
Ndim: 2
Shape: (2, 2)


---

#### I.A. Базовые Операции с Массивами

**Поэлементные операции:** Арифметические операторы (`+`, `-`, `*`, `/`, `**`) применяются к соответствующим элементам массивов **одинаковой формы** (или совместимых по правилам бродкастинга).

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a + b =", a + b)       # [5 7 9]
print("b - a =", b - a)       # [3 3 3]
print("a * b =", a * b)       # [ 4 10 18]
print("b / a =", b / a)       # [4.  2.5 2. ] (dtype становится float)
print("a ** 2 =", a ** 2)     # [1 4 9]

a + b = [5 7 9]
b - a = [3 3 3]
a * b = [ 4 10 18]
b / a = [4.  2.5 2. ]
a ** 2 = [1 4 9]


**Операции с векторами (1D массивы):**
*   **Умножение на скаляр:** `vector * scalar` (поэлементно).
*   **Сложение/вычитание векторов:** `vector1 + vector2` (поэлементно, векторы должны быть одинаковой длины).
*   **Скалярное произведение (Dot Product):** Сумма произведений соответствующих элементов. **Важно: векторы должны быть одинаковой длины.**
    *   `np.dot(vector1, vector2)`
    *   `vector1 @ vector2` (предпочтительный синтаксис)

In [4]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print("Скалярное произведение:", v1 @ v2) # 1*4 + 2*5 + 3*6 = 32

Скалярное произведение: 32


**Операции с матрицами (2D массивы):**
*   **Поэлементные операции:** Аналогично векторам (матрицы должны быть одинаковой формы или совместимы).
*   **Матричное умножение:** **Не** поэлементное!
    *   **Правило:** Число столбцов первой матрицы должно быть равно числу строк второй матрицы (A: m x n, B: n x p => C: m x p).
    *   **Вычисление:** Элемент `C[i, j]` = скалярное произведение i-й строки A и j-го столбца B.
    *   **Синтаксис:**
        *   `np.dot(matrix1, matrix2)`
        *   `matrix1 @ matrix2` (предпочтительно)

In [5]:
m1 = np.array([[1, 2], [3, 4]])    # 2x2
m2 = np.array([[5, 6], [7, 8]])    # 2x2
m_prod = m1 @ m2
print("Матричное умножение:\n", m_prod)
# [[1*5+2*7, 1*6+2*8], [3*5+4*7, 3*6+4*8]] = [[19, 22], [43, 50]]

Матричное умножение:
 [[19 22]
 [43 50]]


*   **Транспонирование:** Меняет строки и столбцы местами.
    *   **Синтаксис:** `matrix.T`

In [6]:
m3 = np.array([[1, 2, 3], [4, 5, 6]]) # 2x3
m3_t = m3.T                         # 3x2
print("Исходная:\n", m3)
print("Транспонированная:\n", m3_t)

Исходная:
 [[1 2 3]
 [4 5 6]]
Транспонированная:
 [[1 4]
 [2 5]
 [3 6]]


---

#### I.B. Индексация и Срезы

Доступ к элементам и подмассивам. Индексация начинается с 0.

*   **Одномерные массивы (векторы):**
    *   Индексация: `vector[index]`, `vector[-1]` (последний).
    *   Срезы: `vector[start:stop:step]` (`stop` не включается).
        *   `vector[:n]`: Первые `n` элементов.
        *   `vector[n:]`: Элементы с `n`-го до конца.
        *   `vector[::2]`: Каждый второй элемент.
        *   `vector[::-1]`: Обратный порядок.
*   **Двумерные массивы (матрицы):**
    *   Индексация: `matrix[row_index, col_index]`.
    *   Срезы: `matrix[row_slice, col_slice]`. Каждый срез задается как `start:stop:step`. `:` означает выбор всех элементов по оси.

In [7]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Элемент [1, 2]:", m[1, 2])      # 6
print("Первая строка:", m[0, :])      # [1 2 3] или просто m[0]
print("Второй столбец:", m[:, 1])      # [2 5 8]
print("Подматрица 2x2 верхний левый:", m[:2, :2]) # [[1, 2], [4, 5]]

Элемент [1, 2]: 6
Первая строка: [1 2 3]
Второй столбец: [2 5 8]
Подматрица 2x2 верхний левый: [[1 2]
 [4 5]]


---

#### I.C. Изменение Формы Массивов (`.reshape()`)

Изменяет форму массива, **не меняя общее количество элементов**.


In [8]:
a = np.arange(1, 13) # Массив от 1 до 12 (12 элементов)
print("Исходный:", a, a.shape) # (12,)

# Преобразование в матрицу 3x4
m_3x4 = a.reshape((3, 4))
print("Матрица 3x4:\n", m_3x4, m_3x4.shape) # (3, 4)

# Преобразование обратно в вектор
v_12 = m_3x4.reshape((12,))
print("Обратно в вектор:", v_12, v_12.shape) # (12,)

# Использование -1 для автоматического расчета размера
m_auto = a.reshape((2, -1)) # 2 строки, столбцы рассчитаются автоматически
print("Матрица 2x?: \n", m_auto, m_auto.shape) # (2, 6)

m_auto_col = a.reshape((-1, 1)) # Вектор-столбец
print("Вектор-столбец ?x1: \n", m_auto_col, m_auto_col.shape) # (12, 1)

Исходный: [ 1  2  3  4  5  6  7  8  9 10 11 12] (12,)
Матрица 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4)
Обратно в вектор: [ 1  2  3  4  5  6  7  8  9 10 11 12] (12,)
Матрица 2x?: 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] (2, 6)
Вектор-столбец ?x1: 
 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] (12, 1)


---

#### I.D. Бродкастинг (Транслирование)

Механизм выполнения операций над массивами **разных форм**, если они **совместимы**. NumPy автоматически "растягивает" массив меньшей размерности.

**Правила совместимости (справа налево по осям):**
1.  Размерности равны.
2.  Одна из размерностей равна 1.

**Примеры:**
*   **Скаляр и массив:** Скаляр "растягивается" до формы массива.


In [9]:
m = np.array([[1, 2], [3, 4]])
print("Матрица + скаляр:\n", m + 10) # [[11, 12], [13, 14]]

Матрица + скаляр:
 [[11 12]
 [13 14]]


*   **Вектор и матрица:**
    *   Вектор-строка (1D массив) транслируется по строкам матрицы (если число элементов вектора = числу столбцов матрицы).
    *   Вектор-столбец (созданный через `reshape(-1, 1)`) транслируется по столбцам матрицы (если число элементов вектора = числу строк матрицы).

In [10]:
m = np.array([[1, 2, 3], [4, 5, 6]]) # 2x3
v_row = np.array([10, 20, 30])        # (3,) -> транслируется как строка
v_col = np.array([100, 200]).reshape(-1, 1) # (2, 1) -> транслируется как столбец

print("Матрица + вектор-строка:\n", m + v_row)
# [[ 11  22  33], [ 14  25  36]]
print("Матрица + вектор-столбец:\n", m + v_col)
# [[101 102 103], [204 205 206]]

Матрица + вектор-строка:
 [[11 22 33]
 [14 25 36]]
Матрица + вектор-столбец:
 [[101 102 103]
 [204 205 206]]


**Преимущества:** Краткость кода, высокая производительность (векторизация).

---

#### I.E. Универсальные Функции (ufuncs)

Функции NumPy, выполняющие **поэлементные операции** над массивами. Написаны на C, очень быстрые.

*   **Унарные (1 аргумент):** `np.abs`, `np.sqrt`, `np.exp`, `np.log`, `np.sin`, `np.cos`, `np.round` и др.
*   **Бинарные (2 аргумента):** `np.add`, `np.subtract`, `np.multiply`, `np.divide`, `np.power`, `np.maximum`, `np.minimum`, `np.equal`, `np.less` и др. (Арифметические операторы `+`, `-` и т.д. - это тоже ufuncs).


In [11]:
a = np.array([-1.2, 0, 3.6])
print("sqrt(abs(a)):", np.sqrt(np.abs(a)))

b = np.array([1, 5, 2])
print("maximum(a, b):", np.maximum(a, b)) # Поэлементный максимум

sqrt(abs(a)): [1.09544512 0.         1.8973666 ]
maximum(a, b): [1.  5.  3.6]


---

#### I.F. Генерация Случайных Чисел (`numpy.random`)

Важно для инициализации весов, разделения данных, случайного поиска и т.д.

*   `np.random.rand(d0, ..., dn)`: Равномерное распределение `[0, 1)`. Размеры как аргументы.
*   `np.random.randn(d0, ..., dn)`: Стандартное нормальное распределение (mean=0, std=1). Размеры как аргументы.
*   `np.random.randint(low, high, size)`: Целые числа из `[low, high)`. `high` можно опустить (будет `[0, low)`). `size` задает форму.
*   `np.random.random(size)`: Аналог `rand`, но `size` задается кортежем.
*   `np.random.choice(a, size, replace, p)`: Случайная выборка из массива `a`.
    *   `a`: Массив или целое число (тогда выборка из `np.arange(a)`).
    *   `replace=True`: Выборка с возвращением (элементы могут повторяться).
    *   `replace=False`: Без возвращения.
    *   `p`: Вероятности выбора элементов `a`.
*   **`np.random.seed(seed)`:** Фиксация "зерна" генератора для **воспроизводимости** результатов. Если `seed` одинаковый, последовательность случайных чисел будет идентичной. `seed=None` использует системное время (разные результаты при каждом запуске).

In [12]:
np.random.seed(42) # Фиксируем зерно
print("Randn 2x2 (seed 42):\n", np.random.randn(2, 2))

np.random.seed(42) # Снова то же зерно
print("Randn 2x2 (seed 42) again:\n", np.random.randn(2, 2)) # Будет то же самое

print("Choice [1,2,3] (size=5, replace=True):\n", np.random.choice([1, 2, 3], size=5, replace=True))

Randn 2x2 (seed 42):
 [[ 0.49671415 -0.1382643 ]
 [ 0.64768854  1.52302986]]
Randn 2x2 (seed 42) again:
 [[ 0.49671415 -0.1382643 ]
 [ 0.64768854  1.52302986]]
Choice [1,2,3] (size=5, replace=True):
 [3 2 3 3 3]


---